version: '3'
services:
  home-camera-face-recognition:
    container_name: home-camera-face-recognition
    build:
      context: .
    volumes:
      # Folders
      - './train:/train'
      - './model:/model'
      - './camera:/camera'
    environment:
      # Folders
      - TRAIN_PATH=/train
      - MODEL_PATH=/model
      - MODEL_PATH=/camera
      # Files
      - MODEL_FILE=model.clf
